language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.6"
      env: TOXENV=py26 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.2"
      env: TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy"
      env: TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy3"
      env: TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version; test $TOXENV = "py32-unit" -o $TOXENV = "py32-versioncheck" -o $TOXENV = "pypy3-unit" -o $TOXENV = "pypy3-versioncheck" && pip install --upgrade virtualenv==13.1.2 || /bin/true
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "XUsHJRyW+0hVPeI4VsfPuDtuG9Mhw3bewnr+C5Bu+ojm9xsuFHpNEIIVUeC508ZTz+N676F9+BLSimYt9ZHh2l5u18RP8N1pPIU0B5S7h8iZ74JXCJnRQoyWqN9sKEH+xS6137p3HaJVzXuKuUWtd4JFXOHag9Yhi9knaMQcJTeNaNozGNEc8L65AYRjau2c9B0NGeTQjUb7qEx24Lb0IOMYrWc6jmaUl/AKLggjph5pd89LRP9tXFreVEVfOsi2BAgVVs4vumvefFO97NVzlGXng70JPQF+somuv59/8A0d+FOOwkY7JXl/5WEjPRXIAC190wJGdgwP8wrmSr+BsQh1EAcB9yynsqoJRoKyK2PomGjUxu8t4N/JCpVTUPp3y3p+kVqYGbMcKvMlfnwCuNlWuB8zdfb/0xwQSKxZZCsUVAIodTGRjz+AABWpohs4DNeUfs+i99KKjvDr1Eq3zWVE16VbZB625agB2Noz5dsIAksXyUkulD4YDjwPIa5oX85LGO7ICKvvFJIDWlEU1VccbIlbbeuMtC6dWa7GGkQ/Ycv5iwZ133ry0ajhUn5nx/AxaTqMCFwt/i2eoGVzfOugtSPyS8tXBHTA+9g+wARmu2s2M3vnWZ5XPn8uK0YiPCN15IWQ/nRygTAECkglzPTQzjqRHexQQcbd6FNYx74="
    api_key:
      secure: "eRaIv4nyH2C470RjQ4+gZ8ZnmXUmmcxyC0BMF6KZPZu6olLoN7pu8U2qppD6HRIAzYVilBlgQSkZAr3MrasZUVLbjwU9aiRGupHeGCLMB8NCuS4ducWvAn95AOMfwVaaFErPx+yAVfFSeqbI82eT6UwiXGSdlyMBIsQyPL//nLvIjLTUHMeH+c7LiLCe7e0MecjgDz0xdovGm+zva6JaDSYFL0zT3uyhMuVbrveOp5c+boKC3+DqXn4WukJaVGHkYY8nlh7zv76Ff+Cim7VXiG1WHw3OmAH8vR2STOkma4rKIw2JWAQc+4mNyYPNcLuPV4ZA5NTGkGC6wq1Vhn5btzt0Y8RHuUR56uipd0YCmr9CxCqEfmTHpCOd9yG/Gg8FLGp+1gFTYvE3nrddRpE22XRN5OoB1lnTZ82I77S1lyGAAQtpHBi7YfJj6gZAs4cmLgpmpHH+bRsb9HNCdShv3Lyohhoi/1wwLUCzpOQ3Fk31jDon3lD9ipil44lE/hRR7omj35CyyzE1yefIoqBgKynzVCYXffL3iERybf85qTUDEfrzSequgw84BXjoVWdRSNjbxGQoQBujnUX4sPF4usxvs+RNe0vFik3iX6uNG0Zw7lcqCiomQdc9A/6dtX3HaRcigwKvM5Io4yIiU2JU78tk9ZYVo2YqBWkc1N7csOI="
branches:
  except:
    - "/^noci-.*$/"
